# Generated by Django 5.2.17 on 2026-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_counselorprofile_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
