# Generated by Django 5.2.17 on 2026-09-21 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0003_studentprofile_school_name'),
        ('planning', '0003_planitemexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('wake_time', models.TimeField(blank=True, null=True)),
                ('sleep_time', models.TimeField(blank=True, null=True)),
                ('mobile_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('self_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ('-date', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DailyReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('STUDY', 'Study'), ('TEST', 'Test'), ('REVIEW', 'Review'), ('EXAM', 'Exam'), ('EVENT', 'Event')], max_length=8)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_source', models.CharField(blank=True, choices=[('MANUAL', 'Manual correction'), ('PLAN', 'Same as plan')], max_length=6)),
                ('actual_test_count', models.PositiveIntegerField(blank=True, null=True)),
                ('correct_count', models.PositiveIntegerField(blank=True, null=True)),
                ('wrong_count', models.PositiveIntegerField(blank=True, null=True)),
                ('unanswered_count', models.PositiveIntegerField(blank=True, null=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.chapter')),
                ('plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_items', to='planning.planitem')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='daily_reports.dailyreport')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.topic')),
            ],
            options={
                'ordering': ('ordering', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='daily_report_one_per_student_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.CheckConstraint(condition=models.Q(('self_rating__isnull', True), models.Q(('self_rating__gte', 1), ('self_rating__lte', 20)), _connector='OR'), name='daily_report_rating_1_to_20'),
        ),
        migrations.AddConstraint(
            model_name='dailyreportitem',
            constraint=models.UniqueConstraint(condition=models.Q(('plan_item__isnull', False)), fields=('report', 'plan_item'), name='daily_report_one_row_per_plan_item'),
        ),
    ]
