# Generated by Django 5.2.17 on 2026-09-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportitem',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportitem',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dailyreportitem',
            name='resource',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dailyreportitem',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
