# Generated by Django 5.2.17 on 2026-09-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0002_dailyreportitem_end_time_dailyreportitem_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
