# Generated by Django 5.2.17 on 2026-10-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0003_dailyreport_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='source',
            field=models.CharField(choices=[('WEB', 'Web'), ('TELEGRAM', 'Telegram')], default='WEB', max_length=8),
        ),
        migrations.AddField(
            model_name='dailyreportitem',
            name='source',
            field=models.CharField(choices=[('WEB', 'Web'), ('TELEGRAM', 'Telegram')], default='WEB', max_length=8),
        ),
    ]
