# Generated by Django 5.2.17 on 2026-09-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0003_studentprofile_school_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='accounts.counselorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ('-start_date', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='planning.plan')),
            ],
            options={
                'ordering': ('date', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('STUDY', 'Study'), ('TEST', 'Test'), ('REVIEW', 'Review'), ('EXAM', 'Exam'), ('EVENT', 'Event')], max_length=8)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('planned_duration_minutes', models.PositiveIntegerField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('test_count', models.PositiveIntegerField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.chapter')),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.planday')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.topic')),
            ],
            options={
                'ordering': ('ordering', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='StudentFixedCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SCHOOL', 'School'), ('CLASS', 'Class'), ('SPORTS', 'Sports'), ('COMMUTE', 'Commute'), ('OTHER', 'Other')], max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_commitments', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ('weekday', 'start_time', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='planning_plan_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='planday',
            constraint=models.UniqueConstraint(fields=('plan', 'date'), name='planning_unique_day_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='planitem',
            constraint=models.CheckConstraint(condition=models.Q(('planned_duration_minutes__gt', 0)), name='planning_item_positive_duration'),
        ),
        migrations.AddConstraint(
            model_name='planitem',
            constraint=models.CheckConstraint(condition=models.Q(('test_count__isnull', True), ('test_count__gt', 0), _connector='OR'), name='planning_item_positive_test_count'),
        ),
    ]
