# Generated by Django 5.2.17 on 2026-09-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planitem',
            name='planning_item_positive_duration',
        ),
        migrations.AlterField(
            model_name='planitem',
            name='planned_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='planitem',
            constraint=models.CheckConstraint(condition=models.Q(('planned_duration_minutes__isnull', True), ('planned_duration_minutes__gt', 0), _connector='OR'), name='planning_item_positive_duration'),
        ),
    ]
