# Generated by Django 5.2.17 on 2026-09-21 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_school_name'),
        ('planning', '0002_remove_planitem_planning_item_positive_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanItemExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial')], max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('current_session_started_at', models.DateTimeField(blank=True, null=True)),
                ('accumulated_seconds', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='planning.planitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_executions', to='accounts.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('student',), name='planning_one_active_timer_per_student')],
            },
        ),
    ]
