# Generated by Django 5.2.17 on 2026-09-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_planitemexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitemexecution',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('NOT_DONE', 'Not done')], max_length=12),
        ),
    ]
