# Generated by Django 5.2.17 on 2026-10-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_planitemexecution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitemexecution',
            name='source',
            field=models.CharField(choices=[('WEB', 'Web'), ('TELEGRAM', 'Telegram')], default='WEB', max_length=8),
        ),
    ]
