# Generated by Django 5.2.17 on 2026-09-30 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_studentprofile_school_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConnectionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_telegram_tokens', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_connection_tokens', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TelegramGroupConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField()),
                ('chat_title', models.CharField(blank=True, max_length=255)),
                ('chat_type', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_group_connections', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Telegram Group Connection',
                'ordering': ('-connected_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='telegram_one_active_group_per_student'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('telegram_chat_id',), name='telegram_one_student_per_group')],
            },
        ),
        migrations.CreateModel(
            name='TelegramStudentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('telegram_username', models.CharField(blank=True, max_length=64, null=True)),
                ('telegram_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_student_connections', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Telegram Student Connection',
                'ordering': ('-connected_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='telegram_one_active_user_per_student'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('telegram_user_id',), name='telegram_one_student_per_user')],
            },
        ),
    ]
