# Generated by Django 5.2.17 on 2026-09-30 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_school_name'),
        ('telegram', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramstudentconnection',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramstudentconnection',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramstudentconnection',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TelegramAdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ENABLE', 'Enable'), ('DISABLE', 'Disable'), ('SUSPEND', 'Suspend'), ('RESUME', 'Resume'), ('BAN', 'Ban'), ('UNBAN', 'Unban'), ('GROUP_LOCK', 'Group lock'), ('GROUP_UNLOCK', 'Group unlock'), ('RESEND_PLAN', 'Resend plan')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('success', models.BooleanField(default=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_admin_actions', to=settings.AUTH_USER_MODEL)),
                ('group_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.telegramgroupconnection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_admin_logs', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Telegram Admin Action Log',
                'ordering': ('-created_at',),
            },
        ),
    ]
